### ISSUE TITLE
OSS Index Package Limit (128 max)

### ISSUE THREAD

**Issue by RicoFactset** [sonatype-nexus-community/bach#15]
Hello,

OSS Index does not allow scanning more than 128 packages at a time.

Expected behavior
Sends 128 packages at a time
Error Message
{"code":400,"message":"Request for more than 128 components"}

Output:
GuzzleHttp\Exception\ClientException  : Client error: `POST https://ossindex.sonatype.org/api/v3/component-report` resulted in a `400 Bad Request` response:
{"code":400,"message":"Request for more than 128 components"}

Same issue is fixed here: https://github.com/digitalcoyote/NuGetDefense/issues/37

Thanks!

**Comment by DarthHater** [comment]
@RicoFactset that is correct, what we tend to do (and I believe we've done in newer versions), is batch requests if there are more than 128 components.

**Comment by PlesnikJakub** [comment]
Hi @DarthHater this seems to be still an issue. 
Is there anything that can be done?

**Comment by DarthHater** [comment]
@PlesnikJakub https://github.com/sonatype-nexus-community/bach/pull/20 sorry! Been having fun writing too much Java lately, if you can give that a shot, it SHOULD fix things for you.

**Comment by PlesnikJakub** [comment]
@DarthHater I tested it on my project with 140+ dependencies and it solved the issue 👍 good job and thank you 😊

**Comment by DarthHater** [comment]
No problem! Glad it helped @PlesnikJakub , in the nearish future we should have some more cool work to do on Bach.
