### ISSUE TITLE
[CI] basic composer checks

### ISSUE THREAD

**Issue by jkowalleck** [sonatype-nexus-community/bach#26]
CI is currently clacking the following check

1. `composer validate`
   check if the `composer.json` (and `composer.lock`) are valid (and matching each other)
2. `composer check-platform-reqs`  
   needed to see if all requirements of the package are met in the CI system

this is a followup of #22

**Comment by madpah** [comment]
From my understanding - `composer validate` is really only required prior to us publishing to packagist (see #35)

I'm adding `composer check-platform-reqs` in PR #36.

FYI: @bhamail, @hboutemy

**Comment by jkowalleck** [comment]
@madpah 
at this point `composer validate` is used as a regression test to see if the `composer.lock` file is up to date and matches `composer.json`.

since https://github.com/sonatype-nexus-community/bach/pull/36/files#r697841516 
was intriduced, it all makes no sence anymore. (bad idea?)
the lock-file is already being ignored, so no need to check or validity ...

**Comment by madpah** [comment]
Understood @jkowalleck - will close this issue then. Thanks!
