### ISSUE TITLE
broken CI tests

### ISSUE THREAD

**Issue by jkowalleck** [sonatype-nexus-community/bach#28]
after the pre-mature merge of #25 (see https://github.com/sonatype-nexus-community/bach/pull/25/files#r616211738)
the CI tests were broken: https://app.circleci.com/pipelines/github/sonatype-nexus-community/bach/105/workflows/a64c8850-244a-43b6-aba4-df980dcbf942/jobs/144

this needs to be sorted out and be fixed.

**Comment by madpah** [comment]
@bhamail - can you re-run CI against this branch please? I suspect it may now pass? If not I can fork and work on it.

**Comment by bhamail** [comment]
@madpah I tried to fire off come the the failed CI builds, but nothing really appears to have started. Unless @jkowalleck objects, I suspect you creating a fork makes sense. Thanks!

**Comment by madpah** [comment]
This is resolved by #36
