### ISSUE TITLE
Parse composer.lock file

### ISSUE THREAD

**Issue by ken-duck** [sonatype-nexus-community/bach#4]
The composer.lock file contains more dependency information. We need to be able to parse this file as a dependency source as well.

**Comment by jkowalleck** [comment]
from the code it looks like this one is implemented, already.

**Comment by DarthHater** [comment]
Yep! @jkowalleck I think a combo of @allisterb and myself implemented this. I'll go ahead and close this for now (feel free to open other issues if you find something odd!)
